### ISSUE TITLE
Implement Prettier checking on GitHub workflow

### ISSUE THREAD

**Issue by vilhelmprytz** [pterodactyl-installer/pis-bot#10]

**Comment by Linux123123** [comment]
It should be there, because `eslint` is checking for it and we are running `eslint` on every workflow run.

https://github.com/pterodactyl-installer/pis-bot/blob/91bdb0879977e91d0651b6c6df5cbce3b3d26bc2/.eslintrc.json#L16

**Comment by vilhelmprytz** [comment]
Sorry, missed that. Seems to work just fine! Closing.
